### ISSUE TITLE
Rokanthemes_Brand: «Unique constraint violation found» on assigning 2 products at once to a brand

### ISSUE THREAD

**Issue by dmitrii-fediuk** [decormarket-com/core#8]
![02](https://user-images.githubusercontent.com/83204/66591120-090d0680-ebb4-11e9-9d1b-55ee43851378.png)

[upwork.com/messages/rooms/room_057397d654dd318954c2a77a38af751d/story_adf5c2cc420e61b714221a71be13d454](https://www.upwork.com/messages/rooms/room_057397d654dd318954c2a77a38af751d/story_adf5c2cc420e61b714221a71be13d454)

**Comment by dmitry-fedyuk** [comment]
It is caused by https://github.com/decormarket-com/core/issues/9

**Comment by dmitrii-fediuk** [comment]
Fixed by:
```
ALTER TABLE rokanthemes_brand_product CHANGE COLUMN product_id product_id int(11) UNSIGNED NOT NULL COMMENT 'Product ID';
```
